### ISSUE TITLE
Error on page with description of ebook

### ISSUE THREAD

**Issue by Morgensohn** [standardebooks/miguel-de-cervantes-saavedra_don-quixote_john-ormsby#1]
On the page describing the ebook, it says (my bold)

> Many scenes (like Quixote’s attack on the windmills) and characters (like **Sanch** Panza and Lothario) are so famous that they’re ingrained in our collective culture.

where it probably should be **Sancho**.

(Additionally, where can one find the source for the description pages? I looked and couldn't find it...) 

Thanks for saving these ebooks!

**Comment by acabal** [comment]
Thanks for catching that, this should be fixed now and the updated ebook should be live.

The description pages are generally written by the producer of the ebook, so there is no other source.  They are also released to the public domain, along with all other contributions our producers make.  See the `content.opf` file for more details, including metadata on who wrote the description :)

**Comment by acabal** [comment]
Fixed with 244d9929a251be2eb71fff898dda2f87905c2a5a
