### ISSUE TITLE
Error in correction commit 5dfa43c

### ISSUE THREAD

**Issue by rrthomas** [standardebooks/miguel-de-cervantes-saavedra_don-quixote_john-ormsby#10]
Out of curiosity, I had a look at this commit to see what it corrected. It's a little hard to see on GitHub, as it doesn't highlight the actual changes within a line, so I may have missed other corrections, but the change from "any where" to "anywhere" is incorrect: the sense is "if there happen to be any [bears and/or wolves] where…

**Comment by acabal** [comment]
Hi there, it looks like this was already fixed in a subsequent commit.

**Comment by rrthomas** [comment]
Oops, sorry!
