### ISSUE TITLE
Add illustrations to the ebook

### ISSUE THREAD

**Issue by asciipip** [standardebooks/miguel-de-cervantes-saavedra_don-quixote_john-ormsby#12]
The [Project Gutenberg edition of _Don Quixote_](https://www.gutenberg.org/files/996/996-h/996-h.htm) includes a number of illustrations made by Gustave Doré. Would it be useful to include those illustrations in the Standard Ebooks edition, too?

**Comment by acabal** [comment]
No, we exclude decorative illustrations as a matter of process.
